package aplikasi_wargar;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel; // Untuk DefaultTableModel
import java.sql.Connection; // Untuk Connection
import java.sql.PreparedStatement; // Untuk PreparedStatement
import java.sql.ResultSet; // Untuk ResultSet
import java.sql.SQLException; // Untuk SQLException
import javax.swing.JOptionPane; // Untuk JOptionPane
import java.sql.DriverManager; // Untuk DriverManager

import dao.TransaksiDAO;
import model.Transaksi;

/**
 *
 * @author Tegar 
 */
public class form_utama extends javax.swing.JFrame {
 
    private Connection connection;
    
// Metode untuk mendapatkan ID yang dipilih dari tabel
private int getSelectedIdFromTable() {
    int selectedRow = tabel_transaksi.getSelectedRow(); // jTable1 adalah nama variabel tabel Anda

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data di tabel terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        return -1;
    }

    // Ambil nilai dari kolom pertama
    Object value = tabel_transaksi.getValueAt(selectedRow, 0);
    
    // Periksa apakah nilai dapat dikonversi menjadi integer
    if (value != null && value instanceof Number) {
        int selectedId = ((Number) value).intValue();
        System.out.println("ID yang dipilih: " + selectedId);  // Log ID untuk debugging
        return selectedId;
    } else {
        JOptionPane.showMessageDialog(this, "ID tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        return -1;
    }
}

 
    
    public form_utama() {
        initComponents();
        connectToDatabase();
        
    tampilkanDataKeTabel(); // Panggil metode untuk menampilkan data di tabel
    }
     // Method untuk koneksi ke database
    private void connectToDatabase() {
        try {
        String url = "jdbc:mysql://localhost:3306/pert4_rpl_tegar"; // Ganti dengan nama database Anda
        String user = "root"; // Ganti dengan username database Anda
        String password = ""; // Ganti dengan password database Anda
            // Inisialisasi koneksi
            connection = DriverManager.getConnection(url, user, password);
            System.out.println("Koneksi ke database berhasil!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Koneksi ke database gagal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Jangan lupa untuk menutup koneksi saat aplikasi ditutup
    protected void finalize() throws Throwable {
        if (connection != null && !connection.isClosed()) {
            connection.close();
        }
        super.finalize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        total_harga = new javax.swing.JTextField();
        harga_makanan = new javax.swing.JTextField();
        harga_minuman = new javax.swing.JTextField();
        jumlah_bayar = new javax.swing.JTextField();
        jumlah_kembalian = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_setData = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("NAMA MAKANAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("HARGA MAKANAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("NAMA MINUMAN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("HARGA MINUMAN");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("TOTAL HARGA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("JUMLAH BAYAR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("JUMLAH KEMBALIAN");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("WARKOP TEGAR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("APLIKASI WARGAR");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indomie Goreng ", "Indomie Rebus", "Roti Bakar", "Pancong" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh Manis", "Es Milo", "Es Teh Tarik", "Es Jasjus\t" }));

        total_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_hargaActionPerformed(evt);
            }
        });

        harga_makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_makananActionPerformed(evt);
            }
        });

        harga_minuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_minumanActionPerformed(evt);
            }
        });

        jumlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_bayarActionPerformed(evt);
            }
        });

        jumlah_kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_kembalianActionPerformed(evt);
            }
        });

        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHitung.setText("HITUNG JUMLAH PEMBELIAN");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnBayar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Pelanggan", "Makan", "Harga Makan", "Minum", "Harga Minum", "Total Harga", "Jumlah Bayar", "Jumlah Kembalian"
            }
        ));
        tabel_transaksi.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabel_transaksi);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("NAMA PELANGGAN");

        nama_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pelangganActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSimpan.setText("SIMPAN DATA");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_edit.setText("EDIT DATA");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_setData.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_setData.setText("SET DATA");
        btn_setData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setDataActionPerformed(evt);
            }
        });

        btn_hapus.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_hapus.setText("HAPUS DATA");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox2, 0, 171, Short.MAX_VALUE)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(harga_minuman, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(harga_makanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jumlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlah_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_setData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga_makanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga_minuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit)
                            .addComponent(btnClear)
                            .addComponent(btnBayar))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btn_setData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void total_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_hargaActionPerformed

    private void harga_makananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_makananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_makananActionPerformed

    private void harga_minumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_minumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_minumanActionPerformed

    private void jumlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_bayarActionPerformed

    private void jumlah_kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_kembalianActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
         // Ambil nilai total harga dan jumlah bayar
        int totalHarga = Integer.parseInt(total_harga.getText());
        int jumlahBayar = Integer.parseInt(jumlah_bayar.getText());

        // Hitung kembalian
        int kembalian = jumlahBayar - totalHarga;
        jumlah_kembalian.setText(String.valueOf(kembalian));

        if (kembalian < 0) {
            JOptionPane.showMessageDialog(this, "Jumlah bayar kurang!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBayarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
         // Bersihkan semua field
        nama_pelanggan.setText("");
        total_harga.setText("");
        harga_makanan.setText("");
        harga_minuman.setText("");
        jumlah_bayar.setText("");
        jumlah_kembalian.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
       // Harga makanan
        int hargaMakanan = 0;
        switch (jComboBox1.getSelectedItem().toString().trim()) {
            case "Indomie Goreng":
                hargaMakanan = 8000;
                break;
            case "Indomie Rebus":
                hargaMakanan = 7000;
                break;
            case "Roti Bakar":
                hargaMakanan = 10000;
                break;
            case "Pancong":
                hargaMakanan = 5000;
                break;
        }
        harga_makanan.setText(String.valueOf(hargaMakanan));

        // Harga minuman
        int hargaMinuman = 0;
        switch (jComboBox2.getSelectedItem().toString().trim()) {
            case "Es Teh Manis":
                hargaMinuman = 4000;
                break;
            case "Es Milo":
                hargaMinuman = 6000;
                break;
            case "Es Teh Tarik":
                hargaMinuman = 5000;
                break;
            case "Es Jasjus":
                hargaMinuman = 3000;
                break;
                 }
        harga_minuman.setText(String.valueOf(hargaMinuman));
        // Hitung total harga
        int totalHarga = hargaMakanan + hargaMinuman;
        total_harga.setText(String.valueOf(totalHarga));
    }//GEN-LAST:event_btnHitungActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void nama_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pelangganActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // Ambil data dari form
    String namaPelanggan = nama_pelanggan.getText();
    String namaMakanan = jComboBox1.getSelectedItem().toString();
    int hargaMakanan = Integer.parseInt(harga_makanan.getText());
    String namaMinuman = jComboBox2.getSelectedItem().toString();
    int hargaMinuman = Integer.parseInt(harga_minuman.getText());
    int totalHarga = Integer.parseInt(total_harga.getText());
    int jumlahBayar = Integer.parseInt(jumlah_bayar.getText());
    int kembalian = Integer.parseInt(jumlah_kembalian.getText());

    // Buat objek Transaksi dan simpan ke database menggunakan TransaksiDAO
    Transaksi transaksi = new Transaksi();
    transaksi.setNama_pelanggan(namaPelanggan);
    transaksi.setNama_makanan(namaMakanan);
    transaksi.setHarga_makanan(hargaMakanan);
    transaksi.setNama_minuman(namaMinuman);
    transaksi.setHarga_minuman(hargaMinuman);
    transaksi.setTotal_harga(totalHarga);
    transaksi.setJumlah_bayar(jumlahBayar);
    transaksi.setKembalian(kembalian);

    TransaksiDAO transaksiDAO = new TransaksiDAO();
    transaksiDAO.saveTransaksi(transaksi);

    JOptionPane.showMessageDialog(null, "Data transaksi berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
    tampilkanDataKeTabel(); // Panggil metode untuk menampilkan data setelah berhasil disimpan
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
           // Ambil ID dari data yang dipilih di tabel
    int selectedRow = tabel_transaksi.getSelectedRow(); // Ambil baris yang dipilih
    
    if (selectedRow == -1) {
        // Menampilkan pesan jika ID tidak valid
        JOptionPane.showMessageDialog(null, "Pilih baris yang valid untuk diedit", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
     
    // Ambil ID transaksi dari kolom pertama di baris yang dipilih
    int selectedId = Integer.parseInt(tabel_transaksi.getValueAt(selectedRow, 0).toString());

    // Ambil data dari form
    String namaPelanggan = nama_pelanggan.getText();
    String namaMakanan = jComboBox1.getSelectedItem().toString();
    int hargaMakanan = Integer.parseInt(harga_makanan.getText());
    String namaMinuman = jComboBox2.getSelectedItem().toString();
    int hargaMinuman = Integer.parseInt(harga_minuman.getText());
    int totalHarga = Integer.parseInt(total_harga.getText());
    int jumlahBayar = Integer.parseInt(jumlah_bayar.getText());
    int kembalian = Integer.parseInt(jumlah_kembalian.getText());

    // Instance TransaksiDAO
    TransaksiDAO transaksiDAO = new TransaksiDAO();
    
    // Update data di database menggunakan TransaksiDAO
    transaksiDAO.updateTransaksi(selectedId, namaPelanggan, namaMakanan, hargaMakanan, namaMinuman, hargaMinuman, totalHarga, jumlahBayar, kembalian);

    // Tampilkan pesan sukses
    JOptionPane.showMessageDialog(null, "Data transaksi berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

    // Panggil metode untuk menampilkan data setelah berhasil diperbarui
    tampilkanDataKeTabel(); 
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_setDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setDataActionPerformed
              // Ambil data dari baris yang dipilih di tabel
    int selectedRow = tabel_transaksi.getSelectedRow(); // Ambil baris yang dipilih
    if (selectedRow != -1) { // Pastikan ada baris yang dipilih
        try {
            // Ambil data dari kolom yang sesuai
            nama_pelanggan.setText(tabel_transaksi.getValueAt(selectedRow, 1).toString());  // Kolom 1 untuk nama_pelanggan
            harga_makanan.setText(tabel_transaksi.getValueAt(selectedRow, 3).toString());    // Kolom 3 untuk harga_makanan
            harga_minuman.setText(tabel_transaksi.getValueAt(selectedRow, 5).toString());    // Kolom 5 untuk harga_minuman
            total_harga.setText(tabel_transaksi.getValueAt(selectedRow, 6).toString());      // Kolom 6 untuk total_harga
            jumlah_bayar.setText(tabel_transaksi.getValueAt(selectedRow, 7).toString());    // Kolom 7 untuk jumlah_bayar
            jumlah_kembalian.setText(tabel_transaksi.getValueAt(selectedRow, 8).toString()); // Kolom 8 untuk kembalian

            // Menangani ComboBox berdasarkan pilihan sebelumnya di tabel
            String namaMakanan = tabel_transaksi.getValueAt(selectedRow, 2).toString().trim(); // Kolom 2 untuk nama_makanan
            switch (namaMakanan) {
                case "Indomie Goreng":
                    jComboBox1.setSelectedIndex(0);
                    break;
                case "Indomie Rebus":
                    jComboBox1.setSelectedIndex(1);
                    break;
                case "Roti Bakar":
                    jComboBox1.setSelectedIndex(2);
                    break;
                case "Pancong":
                    jComboBox1.setSelectedIndex(3);
                    break;
                default:
                    jComboBox1.setSelectedIndex(-1); // Jika tidak ditemukan, set ke index -1
            }

            String namaMinuman = tabel_transaksi.getValueAt(selectedRow, 4).toString().trim(); // Kolom 4 untuk nama_minuman
            switch (namaMinuman) {
                case "Es Teh Manis":
                    jComboBox2.setSelectedIndex(0);
                    break;
                case "Es Milo":
                    jComboBox2.setSelectedIndex(1);
                    break;
                case "Es Teh Tarik":
                    jComboBox2.setSelectedIndex(2);
                    break;
                case "Es Jasjus":
                    jComboBox2.setSelectedIndex(3);
                    break;
                default:
                    jComboBox2.setSelectedIndex(-1); // Jika tidak ditemukan, set ke index -1
            }
        } catch (NumberFormatException e) {
            // Tangani error jika data yang diambil tidak bisa diubah ke tipe data yang sesuai
            JOptionPane.showMessageDialog(this, "Data yang diambil tidak valid. Pastikan data dalam format yang benar.");
        }
    } else {
        // Tampilkan pesan jika tidak ada baris yang dipilih
        JOptionPane.showMessageDialog(this, "Silakan pilih data dari tabel.");
    }
    }//GEN-LAST:event_btn_setDataActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // Ambil ID dari data yang dipilih di tabel
    int selectedRow = tabel_transaksi.getSelectedRow(); // Ambil baris yang dipilih
    
    if (selectedRow == -1) {
        // Menampilkan pesan jika ID tidak valid
        JOptionPane.showMessageDialog(null, "Pilih baris yang valid untuk dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Ambil ID transaksi dari kolom pertama di baris yang dipilih
    int selectedId = Integer.parseInt(tabel_transaksi.getValueAt(selectedRow, 0).toString());

    // Instance TransaksiDAO
    TransaksiDAO transaksiDAO = new TransaksiDAO();
    
    // Hapus data dari database menggunakan TransaksiDAO
    transaksiDAO.deleteTransaksi(selectedId);

    // Tampilkan pesan sukses
    JOptionPane.showMessageDialog(null, "Data transaksi berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

    // Panggil metode untuk menampilkan data setelah berhasil dihapus
    tampilkanDataKeTabel(); 
    }//GEN-LAST:event_btn_hapusActionPerformed

    
    private void tampilkanDataKeTabel() {
    DefaultTableModel model = (DefaultTableModel) tabel_transaksi.getModel();
    model.setRowCount(0); // Hapus semua data di tabel terlebih dahulu

    String sql = "SELECT * FROM transaksi";

    try {
        PreparedStatement pstmt = connection.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getString("id"),
                rs.getString("nama_pelanggan"),
                rs.getString("nama_makanan"),
                rs.getInt("harga_makanan"),
                rs.getString("nama_minuman"),
                rs.getInt("harga_minuman"),
                rs.getInt("total_harga"),
                rs.getInt("jumlah_bayar"),
                rs.getInt("kembalian")
            };
            model.addRow(row);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_setData;
    private javax.swing.JTextField harga_makanan;
    private javax.swing.JTextField harga_minuman;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_bayar;
    private javax.swing.JTextField jumlah_kembalian;
    private javax.swing.JTextField nama_pelanggan;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JTextField total_harga;
    // End of variables declaration//GEN-END:variables
}
